# Generated by Django 5.2.17 on 2026-08-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("unique_id", models.CharField(max_length=32, unique=True)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=191)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nid", models.CharField(blank=True, max_length=32)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=8)),
                ("area", models.TextField(blank=True)),
                ("police_station", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("socio_economic_status", models.CharField(blank=True, max_length=191)),
                ("passport", models.CharField(blank=True, max_length=32)),
                ("patient_type", models.CharField(blank=True, max_length=32)),
                ("is_draft", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name", "unique_id"],
                "indexes": [
                    models.Index(
                        fields=["unique_id"], name="clinical_re_unique__3a74d4_idx"
                    ),
                    models.Index(
                        fields=["registration_no"],
                        name="clinical_re_registr_0348b9_idx",
                    ),
                    models.Index(fields=["phone"], name="clinical_re_phone_082e4d_idx"),
                    models.Index(fields=["name"], name="clinical_re_name_03ef10_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicalObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                (
                    "consulting_doctor_name",
                    models.CharField(blank=True, max_length=191),
                ),
                ("center_name", models.CharField(blank=True, max_length=191)),
                ("cancer_type", models.CharField(blank=True, max_length=191)),
                (
                    "diagnosis_disease_group",
                    models.CharField(blank=True, max_length=191),
                ),
                ("diagnosis_subgroup", models.CharField(blank=True, max_length=191)),
                (
                    "diagnosis_primary_site",
                    models.CharField(blank=True, max_length=191),
                ),
                ("diagnosis_laterality", models.CharField(blank=True, max_length=191)),
                ("grade", models.CharField(blank=True, max_length=191)),
                ("laterality_notes", models.TextField(blank=True)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="clinical_registry.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marital_status", models.CharField(blank=True, max_length=50)),
                ("dietary_habit", models.CharField(blank=True, max_length=191)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("alcohol_history", models.CharField(blank=True, max_length=191)),
                ("radiotherapy_to_chest", models.CharField(blank=True, max_length=191)),
                ("family_cancer_history", models.CharField(blank=True, max_length=191)),
                ("known_mutation", models.CharField(blank=True, max_length=191)),
                ("first_diagnosis_date", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="clinicalobservation",
            index=models.Index(
                fields=["registration_no"], name="clinical_re_registr_3cf93d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalobservation",
            index=models.Index(
                fields=["observed_at"], name="clinical_re_observe_890cf7_idx"
            ),
        ),
    ]
