# Generated by Django 5.2.17 on 2026-08-14 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemotherapyProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle_no",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("protocol_type", models.CharField(max_length=191)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CancerMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=191)),
                ("value", models.CharField(max_length=191)),
                ("unit", models.CharField(max_length=191)),
                ("observed_on", models.DateField()),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancer_markers",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChemotherapyProtocolDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=191)),
                (
                    "chemotherapy_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="clinical_registry.chemotherapyprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("t", models.CharField(blank=True, max_length=191)),
                ("n", models.CharField(blank=True, max_length=191)),
                ("m", models.CharField(blank=True, max_length=191)),
                ("result", models.CharField(blank=True, max_length=191)),
                ("staged_on", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_stagings",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Comorbidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", models.TextField(blank=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comorbidities",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CovidHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=191)),
                ("date", models.DateField(blank=True, null=True)),
                ("vaccine_name", models.CharField(blank=True, max_length=191)),
                ("vaccination_dose", models.CharField(blank=True, max_length=191)),
                (
                    "patient_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covid_histories",
                        to="clinical_registry.patienthistory",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", models.TextField(blank=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisMetastaticSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(blank=True, max_length=191)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metastatic_sites",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Histopathology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", models.TextField(blank=True)),
                ("site", models.TextField(blank=True)),
                ("histology_type", models.TextField(blank=True)),
                ("observed_on", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histopathologies",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Immunohistochemistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_on", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ihc_panels",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "immunohistochemistry panels",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="IHCDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marker_type", models.CharField(max_length=191)),
                ("value", models.CharField(blank=True, max_length=191)),
                (
                    "ihc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="clinical_registry.immunohistochemistry",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MolecularPathology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("specimen", models.CharField(blank=True, max_length=191)),
                ("method", models.CharField(blank=True, max_length=191)),
                ("gene", models.CharField(blank=True, max_length=191)),
                ("exon", models.CharField(blank=True, max_length=191)),
                ("status", models.CharField(blank=True, max_length=191)),
                ("observed_on", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molecular_pathologies",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PastTreatmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_treatment_histories",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PathologicalStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("t", models.CharField(blank=True, max_length=191)),
                ("n", models.CharField(blank=True, max_length=191)),
                ("m", models.CharField(blank=True, max_length=191)),
                ("result", models.CharField(blank=True, max_length=191)),
                ("staged_on", models.DateField(blank=True, null=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathological_stagings",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PathologicalStagingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lvsi", models.CharField(blank=True, max_length=191)),
                ("pni", models.CharField(blank=True, max_length=191)),
                ("margin", models.CharField(blank=True, max_length=191)),
                ("ki67", models.CharField(blank=True, max_length=191)),
                ("staged_on", models.DateField()),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathological_staging_details",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RadiotherapySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("intent", models.TextField(blank=True)),
                ("fraction", models.TextField(blank=True)),
                ("fraction_number", models.TextField(blank=True)),
                ("total_dose", models.TextField(blank=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiotherapy_schedules",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RadiotherapyScheduleModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.TextField(blank=True)),
                (
                    "radiotherapy_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modalities",
                        to="clinical_registry.radiotherapyschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RadiotherapyScheduleSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(blank=True, max_length=191)),
                (
                    "radiotherapy_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="clinical_registry.radiotherapyschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SmokingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=191)),
                (
                    "cigarettes_per_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "duration_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pack_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "quit_period_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "patient_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smoking_histories",
                        to="clinical_registry.patienthistory",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Surgery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("surgery_date", models.DateField()),
                ("modality", models.TextField(blank=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeries",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "surgeries",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalLaterality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=191)),
                (
                    "surgery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lateralities",
                        to="clinical_registry.surgery",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_chemo_protocol", models.TextField(blank=True)),
                ("chemo_cycle_no", models.CharField(blank=True, max_length=191)),
                ("chemo_detail", models.TextField(blank=True)),
                ("chemo_starting_date", models.DateField(blank=True, null=True)),
                ("chemo_end_date", models.DateField(blank=True, null=True)),
                ("line_of_treatment", models.CharField(blank=True, max_length=191)),
                (
                    "disease_progression_status",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "disease_progression_status_date",
                    models.DateField(blank=True, null=True),
                ),
                ("survival_status", models.CharField(blank=True, max_length=191)),
                ("survival_status_date", models.DateField(blank=True, null=True)),
                (
                    "recist_1_target_lesion",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "recist_1_non_target_lesion",
                    models.CharField(blank=True, max_length=191),
                ),
                ("recist_1_new_lesion", models.CharField(blank=True, max_length=191)),
                ("recist_1_result", models.CharField(blank=True, max_length=191)),
                ("recist_1_date", models.DateField(blank=True, null=True)),
                (
                    "recist_1_method_of_estimation",
                    models.CharField(blank=True, max_length=191),
                ),
                ("irecist_target_lesion", models.CharField(blank=True, max_length=191)),
                (
                    "irecist_non_target_lesion",
                    models.CharField(blank=True, max_length=191),
                ),
                ("irecist_new_lesion", models.CharField(blank=True, max_length=191)),
                ("irecist_result", models.CharField(blank=True, max_length=191)),
                ("irecist_date", models.DateField(blank=True, null=True)),
                (
                    "irecist_method_of_estimation",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "pathological_response_rate_target_lesion",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "pathological_response_rate_non_target_lesion",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "pathological_response_rate_new_lesion",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "pathological_response_rate_result",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "pathological_response_rate_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "pathological_method_of_estimation",
                    models.CharField(blank=True, max_length=191),
                ),
                (
                    "progression_free_survival",
                    models.CharField(blank=True, max_length=191),
                ),
                ("overall_survival", models.CharField(blank=True, max_length=191)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_cycles",
                        to="clinical_registry.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="chemotherapyprotocol",
            name="treatment_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chemotherapy_protocols",
                to="clinical_registry.treatmentcycle",
            ),
        ),
        migrations.CreateModel(
            name="ChemotherapyModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", models.CharField(max_length=191)),
                (
                    "treatment_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemotherapy_modalities",
                        to="clinical_registry.treatmentcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentCycleProgressionSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_type", models.CharField(max_length=191)),
                ("value", models.CharField(max_length=191)),
                (
                    "treatment_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_sites",
                        to="clinical_registry.treatmentcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TuberculosisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=191)),
                ("date", models.DateField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True)),
                (
                    "patient_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tb_histories",
                        to="clinical_registry.patienthistory",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
