# Generated by Django 5.2.17 on 2026-08-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_registry", "0003_cancermarker_legacy_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["name", "registry_id"]},
        ),
        migrations.RemoveIndex(
            model_name="patient",
            name="clinical_re_unique__3a74d4_idx",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="unique_id",
        ),
        migrations.AddField(
            model_name="patient",
            name="legacy_unique_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="patient",
            name="registry_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["registry_id"], name="clinical_re_registr_e14f0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["legacy_unique_id"], name="clinical_re_legacy__8d927a_idx"
            ),
        ),
    ]
