# Generated by Django 5.2.17 on 2026-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_registry", "0011_legacy_record_mirrors"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalobservation",
            name="diagnosis_laterility",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="clinicalobservation",
            name="laterality",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicalobservation",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name="patienthistory",
            name="cancer_history",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="patienthistory",
            name="h_o_alcoholism",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="patienthistory",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="patienthistory",
            name="rt_to_chest",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="patienthistory",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
