# Generated by Django 5.2.17 on 2026-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_registry", "0012_clinicalobservation_diagnosis_laterility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemotherapyprotocol",
            name="type",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="clinicalstaging",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ihcdetail",
            name="type",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="immunohistochemistry",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pathologicalstaging",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pathologicalstagingdetail",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smokinghistory",
            name="duration_in_year",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="smokinghistory",
            name="packs_per_year",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="smokinghistory",
            name="per_day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smokinghistory",
            name="quit_period",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="irecist_new_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="irecist_non_target_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="irecist_target_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="pathological_response_rate_new_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="pathological_response_rate_non_target_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="pathological_response_rate_target_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="pfs",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="recist_1_new_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="recist_1_non_target_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycle",
            name="recist_1_target_lasion",
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name="treatmentcycleprogressionsite",
            name="type",
            field=models.CharField(blank=True, max_length=191),
        ),
    ]
