# Generated by Django 5.2.17 on 2026-08-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clinical_registry",
            "0014_rename_clinical_re_registr_3cf93d_idx_patient_obs_registr_973816_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyImportAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_table", models.CharField(max_length=191)),
                ("legacy_row_id", models.PositiveBigIntegerField()),
                ("missing_reference_field", models.CharField(max_length=191)),
                (
                    "missing_reference_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("reason", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "legacy_import_anomalies",
                "ordering": ["source_table", "legacy_row_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_table",
                            "legacy_row_id",
                            "missing_reference_field",
                        ),
                        name="unique_legacy_import_anomaly",
                    )
                ],
            },
        ),
    ]
