# Generated by Django 5.2.17 on 2026-08-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_registry", "0015_legacyimportanomaly"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legacy_id", models.PositiveBigIntegerField(unique=True)),
                ("name", models.CharField(max_length=191)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(max_length=191)),
                ("status", models.CharField(max_length=25)),
                ("remember_token", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "clinical_legacy_users",
                "ordering": ["name", "legacy_id"],
            },
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_profiles",
                to="clinical_registry.doctor",
            ),
        ),
    ]
